#!/bin/bash

CURRENT_DIR="$( cd "$( dirname "$0" )" && pwd )"

# ask for pb-core repo
. "${CURRENT_DIR}/get-core-repo"

# Create missing branches
git checkout -b dev &> /dev/null
git checkout -b pb-core &> /dev/null

# Remote pb-core upstream
git checkout pb-core
git branch --unset-upstream

# Add aliases
# ...

# Configure local git
# ...
