#!/bin/bash

CURRENT_DIR="$(cd "$(dirname "$0")" && pwd)"

# ask for pb-core repo
. "${CURRENT_DIR}/dev-core.sh"

# Save current branch
current_branch=$(git rev-parse --abbrev-ref HEAD)

# Pull pb-core branch from origin
git checkout -b pb-core origin/pb-core &> /dev/null
git checkout pb-core
git branch --unset-upstream &> /dev/null

# Add or update pb-core remote
git remote add pb-core "$pb_repo" 2> /dev/null
git remote set-url pb-core "$pb_repo" 2> /dev/null

# Configure local git (never fetch pb-core tags)
git config --local remote.pb-core.tagopt --no-tags

# Restore current branch
git checkout "$current_branch"
